apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce
data:
  NODE_ENV: "production"
  PORT: "4201"
  MONGO_URI: "mongodb://admin:password123@mongodb-service:27017/ecom?authSource=admin" 