apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: ecommerce
data:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password123
  MONGO_INITDB_DATABASE: ecom 